[package]
name = "rotomdex-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
async-lock = "3.4.2"
async-trait = "0.1.92"
chafa-syms-rs = "0.1.1"
color-eyre = "0.6.5"
colorgrad = "0.8.0"
const_format = "0.2.36"
csscolorparser = "0.8.4"
futures = "0.3.34"
http = "1.5.0"
image = "0.25.10"
itertools = "0.15.0"
lru = "0.18.4"
rapidhash = "4.5.1"
ratatui = { version = "0.30.2", default-features = false, features = ["std"] }
reqwest = { version = "0.12.28", default-features = false, features = [
  "json",
  "rustls-tls-native-roots"
] }
reqwest-middleware = "0.4.2"
rustemon = { git = "https://github.com/zdragg/rustemon", branch = "main", default-features = false }
strum = { version = "0.28.0", features = ["derive"] }
tracing = "0.1.44"
tui-big-text = "0.8.8"
web-time = "1.1.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-fs = "2.2.0"
http-cache-reqwest = "0.16.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
