[package]
name = "rotomdex-core"
version = "0.1.0"
edition = "2024"

[dependencies]
chafa-syms-rs = "0.1.1"
color-eyre = "0.6.5"
colorgrad = "0.8.0"
const_format = "0.2.36"
csscolorparser = "0.8.4"
derive_builder = "0.20.2"
futures = "0.3.34"
http-cache-reqwest = { version = "=1.0.0-alpha.8", features = [
    "manager-cacache"
], optional = true }
image = "0.25.10"
itertools = "0.15.0"
ratatui = { version = "0.30.2", default-features = false, features = ["std"] }
reqwest = "0.13.4"
reqwest-middleware = "0.5.2"
rustemon = { git = "https://github.com/zdragg/rustemon", branch = "merged", default-features = false }
strum = { version = "0.28.0", features = ["derive"] }
tracing = "0.1.44"
tui-big-text = "0.8.8"
web-time = "1.1.0"

[features]
cache = ["dep:http-cache-reqwest", "rustemon/cache"]
