[package]
name = "rotomdex"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.45"
color-eyre = "0.6.5"
colorgrad = "0.8.0"
crossterm = { version = "0.29.0", features = ["event-stream"] }
etcetera = "0.11.0"
fern = "0.7.1"
image = "0.25.10"
itertools = "0.15.0"
log = "0.4.33"
parking_lot = "0.12.5"
ratatui = "0.30.2"
reqwest = "0.13.4"
rustemon = { git = "https://github.com/zdragg/rustemon" }
tokio = { version = "1.53.1", features = ["rt"] }
tokio-stream = "0.1.19"
tui-big-text = "0.8.8"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
