[workspace]
resolver = "3"
members = ["rotomdex-core", "rotomdex-term"]
default-members = ["rotomdex-term"]

[workspace.package]
description = "A Pokédex built for the terminal"
repository = "https://github.com/zdragg/rotomdex"

[profile.dev]
debug = 0

[profile.dev.package."*"]
opt-level = 3  # chafa is very intensive

[profile.release]
opt-level = 3
strip = "symbols"
lto = "thin"
panic = "abort"
codegen-units = 1

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
