[package]
name = "rotomdex-term"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.45"
color-eyre = "0.6.5"
crossterm = { version = "0.29.0", features = ["event-stream"] }
etcetera = "0.11.0"
fern = "0.7.1"
log = "0.4.33"
ratatui = "0.30.2"
rotomdex-core = { path = "../rotomdex-core", features = ["cache"] }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.19"
