[package]
name = "rotomdex-term"
version = "0.1.0"
edition = "2024"
repository.workspace = true
authors.workspace = true
description.workspace = true

[[bin]]
name = "rotomdex"
path = "src/main.rs"

[package.metadata.wix]
upgrade-guid = "ECDABE41-EE95-4D8C-B432-CFAD2A23CB03"
path-guid = "FA7779B8-F60D-4FB2-A088-77D7E1CFD558"
license = false
eula = false

[dependencies]
clap = { version = "4.6.0", features = ["derive"] }
color-eyre = "0.6.5"
crossterm = { version = "0.29.0", features = ["event-stream"] }
etcetera = "0.11.0"
git2 = { version = "0.21.0", features = ["https"] }
indicatif = "0.18.4"
ratatui = "0.30.2"
rotomdex-core = { path = "../rotomdex-core" }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.19"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = ["chrono", "env-filter", "tracing-log"] }
tracing = "0.1.44"
