[package]
name = "rotomdex-web"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
console_log = { version = "1.1.0", features = ["color"] }
futures = "0.3.34"
log = { version = "0.4.33", features = ["std"] }
ratzilla = "0.3.1"
rotomdex-core = { path = "../rotomdex-core", default-features = false }
wasm-bindgen-futures = "0.4.77"
web-sys = { version = "0.3.104", features = ["FontFaceSet"] }
