[package]
name = "rotomdex-web"
version = "0.1.0"
edition = "2024"
description.workspace = true
repository.workspace = true

[package.metadata.dist]
dist = false

[package.metadata.wix]
upgrade-guid = "B85E83C3-A25F-4736-8C41-5F947A13048B"
path-guid = "72DCF918-7FE5-4BD4-AEA8-757E77748062"
license = false
eula = false

[dependencies]
color-eyre = "0.6.5"
futures = "0.3.34"
ratzilla = "0.3.1"
rotomdex-core = { path = "../rotomdex-core" }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
tracing-web = "0.1.3"
