[package]
name = "rotomdex-web"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
futures = "0.3.34"
ratzilla = "0.3.1"
rotomdex-core = { path = "../rotomdex-core" }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["tracing-log"] }
tracing-web = "0.1.3"
wasm-bindgen-futures = "0.4.77"
web-sys = { version = "0.3.104", features = ["FontFaceSet"] }
