name: Deploy to GitHub Pages

on:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Add Rustup Target
        run: rustup target add wasm32-unknown-unknown

      - name: Setup cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.21.1

      - name: Setup Trunk
        run: cargo binstall --no-confirm trunk

      - name: Build with Trunk
        working-directory: rotomdex-web
        run: trunk build --release --public-url /rotomdex/

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v5
        with:
          path: rotomdex-web/dist/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Pages
        uses: actions/deploy-pages@v5
